---
- hosts: cisco
  gather_facts: yes
  connection: local

  tasks:

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          authorize: yes
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"

  - name: show run
    ios_command:
      provider: "{{ connection }}"
      commands:
        - show run
    register: config

  - name: save output
    copy:
      content: "{{ config.stdout[0] }}"
      dest: "/home/$USER/config_backups/{{ansible_date_time.date}}_{{ inventory_hostname }}.txt"
